title: [The title of your site]
description: [A short description of your site's purpose]
show_downloads: false
google_analytics: [tracking ID]

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
