title: Artificial Intelligence
description: Portfolio

show_downloads: false
google_analytics: [tracking ID]

owner:
  url: "https://www.linkedin.com/in/myrna-degano-006839205/"
  email: "myrna.l.degano@gmail.com"
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
